### ISSUE TITLE
JumpHost Tests Failing

### ISSUE THREAD

**Issue by urban-1** [urban-1/publish-over-ssh-plugin#1]
@ChristianLangmann: I have forked your `publish-over-ssh-plugin` proxy branch in order to bring it up to date with the upstream. Most of the migration is done, however, I cannot get the tests to run successfully.... Would you be interested in helping? I can create a pull request so we edit and fix on your fork (which we later push to upstream).

Let me know,
Andreas

**Comment by ChristianLangmann** [comment]
sure, let’s do it!
Christian

**Comment by urban-1** [comment]
Hi again @ChristianLangmann 

All should be done - you should have a pull request. Most of the commits are from the upstream. The last four or so are mine ... you might wanna create another branch before merging :). I am at work now but I will have a look later today. Let me know if there is anything else I need to do.

Cheers,
Andreas
[we should move the conversation under the pull-request ]
